
server:

 #port: 8080

 servlet:

    context-path: /spiderNovel

    
#web:
 # upload-path: E:/     

    
spring:
  servlet:
    multipart:
      # 上传一个文件最大值,默认1M
      max-file-size: 500MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 1000MB     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/novel?useSSL=false&serverTimezone=CTT&characterEncoding=utf8&allowMultiQueries=true

    username: root
    password: tlx123

  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
 # mvc:
  #   static-path-pattern: /static/**
 

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/spider/mapper/*.xml
  type-aliases-package: com.spider.model

  
 


